# Generated by Django 4.2.4 on 2023-08-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prex',
            fields=[
                ('pis', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nasc', models.DateField()),
            ],
        ),
    ]
