# Generated by Django 4.2.4 on 2023-09-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0004_aluno_usuario_prex_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditalAluno',
        ),
    ]
