# Generated by Django 4.2.4 on 2023-09-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0005_delete_editalaluno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('aluno', 'edital')},
        ),
    ]
