# Generated by Django 4.2.4 on 2023-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0006_alter_inscricao_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
