# Generated by Django 4.2.4 on 2023-10-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0007_professor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='n_vagas_t',
            field=models.IntegerField(null=True),
        ),
    ]
