# Generated by Django 4.2.4 on 2023-11-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0009_edital_ata_coleg_edital_ata_cons_edital_pdf_edital'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='justificativa',
            field=models.TextField(null=True),
        ),
    ]
