# Generated by Django 4.2.4 on 2023-11-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_editais', '0010_inscricao_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em andamento', max_length=20),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='pdf_edital',
            field=models.FileField(null=True, upload_to='relatorios/'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=20),
        ),
    ]
